import type { Metadata } from 'next'
import '../globals.css'
import Providers from '@/app/(root)/providers'

import {
	PageHeader,
	PageHeaderDescription,
	PageHeaderHeading,
} from '@/components/components/page-header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<div className="container relative">
					<PageHeader>
						<PageHeaderHeading className="hidden md:block">
							Check out Discuss
						</PageHeaderHeading>
						<PageHeaderHeading className="md:hidden">Discuss</PageHeaderHeading>
						<PageHeaderDescription>
							get started to one of the most vibrant journey of your life time
						</PageHeaderDescription>
					</PageHeader>
					<section>
						<div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
							<Providers>{children}</Providers>
						</div>
					</section>
				</div>
			</body>
		</html>
	)
}
