services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: {}
